/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-04-12 11:38:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Sell&Rent main page</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.navbar {\r\n");
      out.write("    	display: flex;\r\n");
      out.write("    	justify-content: space-between;\r\n");
      out.write("    	align-items: center;\r\n");
      out.write("    	background-color: rgb(0, 0, 0);\r\n");
      out.write("    	padding: 10px 20px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.navbar-left .navbar-logo {\r\n");
      out.write("	    font-size: 32px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	    text-decoration: none;\r\n");
      out.write("	    color: red;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.navbar-right .navbar-button {\r\n");
      out.write("	    margin-left: 10px;\r\n");
      out.write("	    padding: 8px 16px;\r\n");
      out.write("	    background-color: green;\r\n");
      out.write("	    color: blue;\r\n");
      out.write("	    text-decoration: none;\r\n");
      out.write("	    border-radius: 4px;\r\n");
      out.write("	}\r\n");
      out.write("	.content {\r\n");
      out.write("    	background-image: url('images/lamborghini-autentica.jpg');\r\n");
      out.write("    	background-size: cover; /* Resmi içeriğe sığdır */\r\n");
      out.write("        background-position: center; /* Resmi ortala */\r\n");
      out.write("        color: white; /* Yazı rengi */\r\n");
      out.write("        padding: 100px; /* İç boşluk, yazının etrafında boşluk oluşturur */\r\n");
      out.write("        text-align: center; /* Yazıyı ortala */\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        height: 1500px;\r\n");
      out.write("	}\r\n");
      out.write("	.content-text {\r\n");
      out.write("        background-color: rgba(0, 0, 0, 0.5); \r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        max-width: 100%; \r\n");
      out.write("     }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"navbar\">\r\n");
      out.write("        <div class=\"navbar-left\">\r\n");
      out.write("            <a href=\"mainPage.jsp\" class=\"navbar-logo\">Sell&Rent</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-right\">\r\n");
      out.write("            ");
 if (session.getAttribute("loggedInUser") == null) { 
      out.write("\r\n");
      out.write("                <a href=\"register.jsp\" class=\"navbar-button\">Register</a>\r\n");
      out.write("                <a href=\"login.jsp\" class=\"navbar-button\">Login</a>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <span style=\"margin-right: 10px; font-weight: bold;\">\r\n");
      out.write("                    ");
 if (session.getAttribute("loggedInUser") != null) { 
      out.write("\r\n");
      out.write("                        Hoş geldiniz, ");
      out.print( ((com.sellandrent.model_tier.Customer) session.getAttribute("loggedInUser")).getName() );
      out.write("\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("                <a href=\"user-panel.jsp\" class=\"navbar-button\">Kullanıcı Paneli</a>\r\n");
      out.write("                <a href=\"logout.jsp\" class=\"navbar-button\" style=\"background-color: #d9534f;\">Logout</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"content-text\">\r\n");
      out.write("            <h2>Sell&Rent ile Hayallerine Kavuş!</h2>\r\n");
      out.write("            <p>\r\n");
      out.write("                Sell&Rent, araç kiralama işlemlerinizi kolaylaştırmak için tasarlanmış yenilikçi bir platformdur. \r\n");
      out.write("                Geniş araç yelpazemiz arasından dilediğiniz aracı bulabilir, kendi aracınızı kolayca satışa çıkarabilir \r\n");
      out.write("                veya ihtiyacınız olan süre boyunca hayalinizdeki aracı kiralayabilirsiniz. \r\n");
      out.write("                Kullanıcı dostu arayüzümüz ile sorunsuz bir deneyim sunuyoruz. \r\n");
      out.write("                İster lüks bir spor otomobil hayal edin, ister pratik bir aile aracı arayın, \r\n");
      out.write("                Sell&Rent size en iyi seçenekleri sunar. Hemen keşfetmeye başlayın ve otomotiv dünyasının kapılarını aralayın!\r\n");
      out.write("            </p>\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
